[package]
name = "bevy_gltf_collider"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.10.1", features = ["dynamic_linking"] }
bevy_rapier3d = "0.21.0"
serde_json = "1.0"
serde = "1.0"

[dev-dependencies]
rand = "0.8.5"
